### ISSUE TITLE
got a warning from Google playstore

### ISSUE THREAD

**Issue by paulle** [Exodus-Privacy/exodus-android-app#27] opened 2018-04-16 17:02 UTC
Got a warning from playstore, saying please uninstall this app because exodus privacy can harm your device.
??

**Comment by Schoumi** [comment] 2018-04-16 17:05
Do you have a screen of this? or can you make one?

**Comment by stom79** [comment] 2018-04-16 17:16
Strange that it comes from Playstore itself and they let the app on their market. What's your device manufacturer and OS version? Do you have in "Settings" -> "Advanced settings" -> "Security" Something like: "Scan device for security threads"?

**Comment by paulle** [comment] 2018-04-16 17:42
It's a Sony xz device. Running Android 7.

Am 16. April 2018 19:19:37 MESZ schrieb Thomas <notifications@github.com>:
>Strange that it comes from Playstore itself and they let the app on
>their market. What's your device manufacturer and OS version? Do you
>have in "Settings" -> "Advanced settings" -> "Security" Something like:
>"Scan device for security threads"?

-- 
K-9 Mail

**Comment by paulle** [comment] 2018-04-16 17:53
Can't find something like advanced settings, there is only security and display lock. And nothing of scan device for security threads. But in playstore
Is activated play protect.

Am 16. April 2018 19:19:37 MESZ schrieb Thomas <notifications@github.com>:
>Strange that it comes from Playstore itself and they let the app on
>their market. What's your device manufacturer and OS version? Do you
>have in "Settings" -> "Advanced settings" -> "Security" Something like:
>"Scan device for security threads"?

-- 
K-9 Mail

**Comment by Schoumi** [comment] 2018-04-16 18:28
You install from the playstore or from another source ?

**Comment by Schoumi** [comment] 2018-04-16 18:31
Can you take a screenshot even if it's in german. It will help us to find whats going on.

**Comment by klorydryk** [comment] 2018-04-16 22:03
![da75u8px4aagpum jpg large](https://user-images.githubusercontent.com/1232047/38837386-1386c692-41d2-11e8-8ddc-945d1dd5761f.jpg)
Installed via F-Droid, Android 7.1.1 (LineAgeOS), Google Store v9.6.11-all

**Comment by paulle** [comment] 2018-04-16 23:01
I installed from f-droid.


Am 16. April 2018 20:28:27 MESZ schrieb Anthony Chomienne <notifications@github.com>:
>You install from the playstore or from another source ?

-- 
K-9 Mail

**Comment by stom79** [comment] 2018-04-17 05:37
What is the result in "Settings" -> "Google" -> "Security" -> "Google Play Protect"?
There are of course no issues with [the APK from Fdroid](https://www.virustotal.com/file/2d04a249a009e9a238f7fcc232d9d7627a4b0038f0d67a22d1860571742e1570/analysis/1523942572/).

**Comment by paulle** [comment] 2018-04-17 06:37
mtp://%5Busb%3A001,004%5D/Interner%20gemeins.%20Speicher/Pictures/Screenshots/Screenshot_20180416-193531.png
mtp://%5Busb%3A001,004%5D/Interner%20gemeins.%20Speicher/Pictures/Screenshots/Screenshot_20180416-193625.png

**Comment by paulle** [comment] 2018-04-17 07:02
The warning has gone, I changed nothing.

**Comment by kRush-** [comment] 2018-04-20 14:04
![screenshot_20180420-155742](https://user-images.githubusercontent.com/5452485/39055238-f4c82126-44b3-11e8-8d2f-e2e446d86716.png)
Trying to install from f-droid: blocked by play protect, this app could track your location.

**Comment by jawz101** [comment] 2018-04-23 14:40
![screenshot_20180423-093150](https://user-images.githubusercontent.com/14151703/39133648-4c3d6c4a-46da-11e8-8fae-8b39c8c3382d.png)

**Comment by TPS** [comment] 2018-06-03 15:30
I, too, am having this issue, but I obviously trust the build @ F-Droid over the 1 @ GPlay.  Anyone know who to complain to?

**Comment by stom79** [comment] 2018-06-03 18:09
@Schoumi Does the app only query the apps on the device or does it synchronize the db from exodus locally?
If it's the first option, that's true that exodus server through calls (app id & IP) can know what apps are installed on a device.
Also, one sync per day of the db locally will avoid that issue. The app will only need crossing these results with installed apps. It would also fix #29

**Comment by TPS** [comment] 2018-06-04 04:10
@stom79 But the problem isn't that, right?  It's about why the GPlay build passes Play Protect when the F-Droid 1 fails, when they're both (presumably) built from identical source, AFAIK.

**Comment by stom79** [comment] 2018-06-04 05:41
Yes, the app doesn't use product flavors, so the only difference is the app signature. I don't understand why one is flagged and not both, or none of them.
That said, I only highlighted a potential fix for this issue that keeps to be reported even months after the first report. And I guess after complains to Google to fix this FP.

**Comment by ExtremeNerd** [comment] 2018-09-27 08:57
Google, whatsapp etc.. mislead users many times.

I got a warning for using K9 Mail that security standards are outdated and switch to gmail. Heck, I haven't yet seen openpgp in their apps

**Comment by pnu-s** [comment] 2022-01-03 21:05
Closing this for the time being, as we got removed from Google Play Store. We can reopen if the problem comes back.

**Closed by pnu-s** 2022-01-03 21:05 UTC
Labels: question

**Comment by argymeg** [comment] 2022-06-23 19:37
A bit unsure if this counts as the problem coming back, but I just got this again while installing from F-droid. Related to #143 as well, I would assume.
![Screenshot_20220623-203233](https://user-images.githubusercontent.com/7372767/175383105-91eac982-d82a-493f-a99b-170c2ad851ff.png)

**Comment by codeurimpulsif** [comment] 2022-06-29 21:15
@argymeg thanks for this information, yes I think it's related to #143 
Maybe it will be fixed when we republish the app on the Google Play Store soon.
