### ISSUE TITLE
Feature request: Add support for Android 13's themed app icons

### ISSUE THREAD

**Issue by icejuice-enjoyer** [Exodus-Privacy/exodus-android-app#274] opened 2023-05-07 00:40 UTC
Adding support would help better integrate the app icon in launchers on Android 13+ devices.

https://developer.android.com/about/versions/13/features#themed-app-icons
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming

**Comment by Jean-BaptisteC** [comment] 2023-05-13 10:10
Duplicate of #214
This feature is in next version planned soon

**Closed by Jean-BaptisteC** 2023-05-13 10:10 UTC
