### ISSUE TITLE
remove limitation that the app must be installed by Google Play

### ISSUE THREAD

**Issue by eighthave** [Exodus-Privacy/exodus-android-app#26] opened 2018-04-16 12:45 UTC
My phone does not have Google Play, but I'd still like to use this scanner.  Right now, it returns no apps, saying that it didn't find any that were installed by Google Play.  But I have a bunch of apps that came from other F-Droid repos besides _f-droid.org_.

**Comment by U039b** [comment] 2018-04-18 20:59
Hi @eighthave!

We need to talk together and determine how εxodus would analyze applications delivered by F-Droid ;-)

**Comment by eighthave** [comment] 2018-04-18 21:52
yes, sure!  The methods I know for finding and reading APKs installed on
a device return all the APKs.  Are you filtering that list somehow?  Or
is that the result of the API you're using?

**Comment by Schoumi** [comment] 2018-04-19 12:06
I filter app by installation source. I use this https://developer.android.com/reference/android/content/pm/PackageManager.html#getInstallerPackageName(java.lang.String).

The problem is that F-Droid and Yalp don't install themselves apps. Even if F-Droid with Privileged Extension set the correct package. It's not the case for all device.

Since api 21 it's possible to install apps and have the right InstallerPackageName by install the app yourself and not delegate to the System Package Manager: https://developer.android.com/reference/android/content/pm/PackageInstaller.html used with https://developer.android.com/reference/android/content/pm/PackageManager.html#getInstalledPackages(int)

I have made a very simple test that download a package from F-Droid and install it on the device and it works perfectly. The whole code for this take ~200 lines (no treatment of error or anything else but works fine).

I plan in the next month to try to make it right in Yalp since it's Play Store apps and Exodus only analyse Play Store apps for now, but it will be great to have it in F-Droid too.

**Comment by eighthave** [comment] 2018-04-20 08:13
I know about the PackageManager stuff. My question is: why would you
want to filter based on app store or what installed it?  I want to run
the scanner on any app installed on my device.

If you want to improve the InstallerPackageName code in F-Droid, we
would welcome that contribution!

Also, FYI, I know in newer versions of Android, an app cannot set the
installer to anything but itself, so Yalp would not be able to set
packages as if they were installed by Google Play.  Using Privileged
Extension, it should be possible, since it should have full rights to
the system.

**Comment by Schoumi** [comment] 2018-04-20 10:30
Exodus only analyse app from play store. Even if the same app exist on F-Droid or any other source, i can't display a report for this because Exodus hasn't analyse this version and we can't show information that may be false. The Exodus Android App doesn't perform any analysis for now, it retrieve apps on the phone, display permissions and retrieve Exodus Report from the Exodus Server.

For yalp if, the installer is set as yalp package, this is good, i can add it to my filter. the problem is for now, installer for yalp, f-droid or apk installed from sd card is set to Android Package Installer for the majority of users, so it's complicated to know the real source of the package.

If Exodus analyse app from F-Droid the filter will be extended to F-Droid apps.

**Comment by U039b** [comment] 2018-04-20 11:04
Hi!!
I think I have a robust solution for this issue. Since the precious major release of εxodus, I have introduced the Universal Application Identifier. This UAID is computed this way: [SHA1(application_handle+' '+certificate_fingerprint)](https://github.com/Exodus-Privacy/exodus-core/blob/v1/exodus_core/analysis/static_analysis.py#L402).
This identifier is unique for any couple (application, certificate). 

If we use this UAID to identify applications, we do not need to consider the installation source anymore.

**Extra**: this UAID could be used to detect suspicious versions of any application ;-)

**Comment by eighthave** [comment] 2018-04-20 14:50
why not just use the SHA256 of the whole APK file?  That's what F-Droid,
VirusTotal and others use.  F-Droid also uses packageName and
certificate fingerprint for more specific kinds of matching, but the
SHA256 of the whole APK is the canonical ID.

**Comment by stom79** [comment] 2018-04-21 05:58
I tried to build this function to check:

```
    @SuppressLint("PackageManagerGetSignatures")
    public static String getCertificateSHA1Fingerprint(Context context, String packageName) {
        PackageManager pm = context.getPackageManager();
        int flags = PackageManager.GET_SIGNATURES;
        PackageInfo packageInfo = null;
        try {
            packageInfo = pm.getPackageInfo(packageName, flags);
        } catch (PackageManager.NameNotFoundException e) {
            e.printStackTrace();
        }
        assert packageInfo != null;
        Signature[] signatures = packageInfo.signatures;
        byte[] cert = signatures[0].toByteArray();
        InputStream input = new ByteArrayInputStream(cert);
        CertificateFactory cf = null;
        try {
            cf = CertificateFactory.getInstance("X509");
        } catch (CertificateException e) {
            e.printStackTrace();
        }
        X509Certificate c = null;
        try {
            assert cf != null;
            c = (X509Certificate) cf.generateCertificate(input);
        } catch (CertificateException e) {
            e.printStackTrace();
        }
        String hexString = null;
        try {
            MessageDigest md = MessageDigest.getInstance("SHA1");
            assert c != null;
            byte[] a = packageName.getBytes();
            byte[] b = c.getEncoded();
            byte[] sum = new byte[a.length + b.length];
            System.arraycopy(a, 0, sum, 0, a.length);
            System.arraycopy(b, 0, sum, a.length, b.length);
            byte[] publicKey = md.digest(sum);
            hexString = byte2HexFormatted(publicKey);
        } catch (NoSuchAlgorithmException e1) {
            e1.printStackTrace();
        } catch (CertificateEncodingException e) {
            e.printStackTrace();
        }
        assert hexString != null;
        return hexString.toUpperCase();
    }

    private static String byte2HexFormatted(byte[] arr) {
        StringBuilder str = new StringBuilder(arr.length * 2);
        for (byte anArr : arr) {
            String h = Integer.toHexString(anArr);
            int l = h.length();
            if (l == 1) h = "0" + h;
            if (l > 2) h = h.substring(l - 2, l);
            str.append(h.toUpperCase());
        }
        return str.toString();
    }
```
I don't get same results that app_uid returned in the [list of apps](https://github.com/Exodus-Privacy/exodus/wiki/REST_API#get-all-analyzed-applications).

Why UAID is equal to `SHA1(application_handle+' '+certificate_fingerprint)`? As far as the json object returns the handle and certificate_fingerprint, they are no need to concat them? What am I missing here? 
I suspect my issue comes from this concatenation.

**Comment by eighthave** [comment] 2018-04-23 12:05
I wouldn't recommend using `signatures[0].toByteArray();` for anything
new since it does not represent some signatures fully.  It is valid for
APKs to have multiple signatures.  F-Droid has to stick with that for
backwards compatibility reasons.

**Comment by stom79** [comment] 2018-04-23 12:55
OK. In the last version of the code, I use https://github.com/Exodus-Privacy/exodus-android-app/issues/26#issuecomment-383271287
That loops over all signatures

**Comment by CalinouBobine** [comment] 2019-11-27 14:57
Hi, 

I’ve been to CDL2019 and since then, I’ve been trying to clean my phone of all privacy-free apps.
I discovered the Exodus Privacy app and it is really great. Thank you!
I think it would be cool to have a report of the apps installed from F-Droid.

So I post my question here to find out where this ticket stands. 
Is it planned for a future version? Has it been abandoned?

Thank you

**Comment by pnu-s** [comment] 2022-01-03 21:10
Should be included now in the application, closing this

**Closed by pnu-s** 2022-01-03 21:10 UTC
Labels: enhancement, question
