### ISSUE TITLE
App give focus on wrong fragment

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#191] opened 2022-07-26 08:08 UTC
### Issues: 
* Device: Honor 8
* OS: Android 8

How reproduce:
* 1 :
  * Start app
  * Go to trackers tab
  * Consult tracker -> Focus is gived to [recycler_view_app_item](https://github.com/Exodus-Privacy/exodus-android-app/blob/kotlinRewrite/app/src/main/res/layout/recycler_view_app_item.xml)
* 2 : 
    * Start app
    * Consult report
    * Open report on Exodus with this button [openExodusPage ](https://github.com/Exodus-Privacy/exodus-android-app/blob/aadb28a06efb2d81d8290710b999a390cb43211e/app/src/main/res/menu/app_detail_menu.xml#L5)
    * Go back to app -> Focus is gived to [fragment_a_d_trackers](https://github.com/Exodus-Privacy/exodus-android-app/blob/kotlinRewrite/app/src/main/res/layout/fragment_a_d_trackers.xml)

Maybe this issue is specific on device with a little screen ?

**Comment by Jean-BaptisteC** [comment] 2022-08-15 14:02
This bug have a big impact on experience. I'm able to reproduce on Android 5.0 (Smartphones and tablets)
@J-Jamet Is it possible to fix this before release ?

**Comment by J-Jamet** [comment] 2022-08-15 14:04
I'll take a look.

**Comment by J-Jamet** [comment] 2022-09-02 13:13
The problem seems to be reproducible only when an external WebView is opened (after opening a URL), otherwise for the first launch, the bug is not present.

The first hypothesis comes from the loading of the views in the scrolls which are disturbed by the asynchronous recovery of information after a WebView is loaded in memory but no fix has been found yet. 
It is likely that the bug comes from the system, in this case, only a workaround is possible.

**Comment by Jean-BaptisteC** [comment] 2024-02-08 16:51
The second case is fixed
We can fix the first case with CollapsingToolbarLayout but the scroll is infinite
@connyduck any idea how to fix infinite scroll?

**Comment by connyduck** [comment] 2024-02-08 19:15
I'm not sure I understand the problem? Could you post a video or the exact steps to reproduce it please?

**Closed** 2024-02-11 07:02 UTC
Labels: bug
