### ISSUE TITLE
[FEATURE] Notify the user if a previously installed app has a new tracker

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [Exodus-Privacy/exodus-android-app#168] opened 2022-05-12 23:45 UTC
This feature would compare a previous scan to a new scan, and if an app that was already scanned has had a new tracker added, notify the user. This would probably be best implemented by also implementing #94

**Comment by Jean-BaptisteC** [comment] 2022-05-13 19:41
Duplicate of [exodus#427](https://github.com/Exodus-Privacy/exodus/issues/427)
If we add this feature on website, we add this feature on android app.

**Closed by Jean-BaptisteC** 2022-05-13 19:41 UTC

**Comment by ItsIgnacioPortal** [comment] 2022-05-14 05:37
This issue is not a duplicate, as implementing this in the app does not necesarily need any server side modifications.
