### ISSUE TITLE
New features asked

### ISSUE THREAD

**Issue by jfoucry** [Exodus-Privacy/exodus-android-app#448] opened 2024-05-02 09:42 UTC
Is it possible to add sort in applications view· By number of trackers and by permissions in addition of the current sort, by applications name? 

Asked by Paul Martinez (paul.martinezval@tutamail.com) by mail·

**Comment by codeurimpulsif** [comment] 2024-05-02 14:10
Duplicate of #210 and implemented in #441 ;)

**Closed by codeurimpulsif** 2024-05-02 14:10 UTC
